apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: izzzz/python-app
        name: python-app
      volumes:
      - name: python-app-data-mount
        persistentVolumeClaim:
          claimName: python-app