apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4419-python-app:9626b41011ae0911ee5a4ccbc0a066f7273ffea8
          name: python-app
